//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#include "Jamnik.h"

void Jamnik::Aportowanie() {

}

void Jamnik::Zabawa() {

}

