//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#include "Jamnik.h"
using namespace std;

void Jamnik::Aportowanie() {
    cout<<endl<<"aportowanie";

}

void Jamnik::Zabawa() {
    cout<<endl<<"zabawa";
}

