//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H


#include "Pies.h"
#include <string>

class Jamnik : public Pies {
public:
	std::string Imie;
	void Aportowanie();
	void Zabawa();
};

#endif  //_JAMNIK_H
