//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 05.03.2024
//  @ Author :
//
//
#include <iostream>
using namespace std;

#include "Pies.h"
using namespace std;
void Pies::Szczekanie() {
    cout<<endl<<"Szczekanie";

}

