//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 05.03.2024
//  @ Author :
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"
#include <string>

class Pies : public Ssak {
public:
	std::string Rasa;
	std::string Plec;
	void Szczekanie();
};

#endif  //_PIES_H
