//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 05.03.2024
//  @ Author : 
//
//


#include "Pies.h"

void Pies::Szczekanie() {

}

