//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 05.03.2024
//  @ Author :
//
//


#include "Ssak.h"

void Ssak::Jesc() {

}

void Ssak::Pic() {

}

void Ssak::Spac() {

}

