//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 05.03.2024
//  @ Author :
//
//


#if !defined(_SSAK_H)
#define _SSAK_H
#include <string>


class Ssak {
public:
	std::string Rodzaj;
	void Jesc();
	void Pic();
	void Spac();
};

#endif  //_SSAK_H
