//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 05.03.2024
//  @ Author :
//
//
using namespace std;

#include "Ssak.h"

void Ssak::Jesc() {
    cout<<endl<<"jesc";

}

void Ssak::Pic() {
    cout<<endl<<"pic";

}

void Ssak::Spac() {
    cout<<endl<<"spac";

}

