//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Amerykanska.h
//  @ Date : 11.06.2024
//  @ Author :
//
//


#if !defined(_AMERYKANSKA_H)
#define _AMERYKANSKA_H

#include <string>
#include <iostream>
#include <map>
#include "Pizza.h"

class Amerykanska : public Pizza {
public:
	Amerykanska():Pizza(Amerykanska) {}
	~Amerykanska() {}
	virtual Pizza* clone()const{
	return new Amerykanska;}
	void printPizza();
};

#endif  //_AMERYKANSKA_H
