//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Amerykanska.cpp
//  @ Date : 11.06.2024
//  @ Author :
//
//


#include <string>
#include <iostream>
#include <map>
#include "Amerykanska.h"
#include "Pizza.h"

Amerykanska::Amerykanska() {

}

Amerykanska::~Amerykanska() {

}

Pizza Amerykanska::clone() {

}

void Amerykanska::printPizza() {
    cout<<"Amerykanska\n;";
}

