//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pizza.cpp
//  @ Date : 11.06.2024
//  @ Author :
//
//


#include <string>
#include <iostream>
#include <map>
#include "Pizza.h"

Pizza::Pizza(PizzaType type) {

}

Pizza Pizza::Clone() {

}

Pizza::~Pizza() {

}

void Pizza::printPizza() {

}

 Pizza::getType() {

}

