//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pizzeria.cpp
//  @ Date : 11.06.2024
//  @ Author :
//
//


#include <string>
#include <iostream>
#include <map>
#include "Pizzeria.h"
#include "Pizza.h"

Pizzeria::~Pizzeria() {

}

Pizza Pizzeria::createPizza(int type) {

}

Pizzeria Pizzeria::Instance() {

}

Pizzeria::Pizzeria() {
    prototypes[Amerykanska]= new Amerykanska();
    prototypes[Rzymska] = new Rzymska();

}

