//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pizzeria.h
//  @ Date : 11.06.2024
//  @ Author :
//
//


#if !defined(_PIZZERIA_H)
#define _PIZZERIA_H

#include <string>
#include <iostream>
#include <map>
#include "Pizza.h"

class Pizzeria {
public:
	~Pizzeria(){
        delete prototypes[Amerykanska];
        delete prototypes[Rzymska];
	}
	Pizza* createPizza(PizzaType typse){
        return prototypes[type]->clone();
    }
	static Pizzeria* Instance();{
        static Pizzeria *instance = new Pizzeria();
        return instance;
    }
private:
	map<PizzaType,Pizza*> prototypes;
	Pizzeria();
};

#endif  //_PIZZERIA_H
