//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pizza.h
//  @ Date : 11.06.2024
//  @ Author :
//
//


#if !defined(_PIZZA_H)
#define _PIZZA_H

#include <string>
#include <iostream>
#include <map>

class Pizza {
protected:
	Pizza(PizzaType type): pType(type) {}
	friend class Pizzeria;
public:
	Pizza Clone();
	virtual ~Pizza() {};
	virtual void printPizza() =0;
    PizzaType getType()const{
    return pType};
protected:
    PizzaType pType;
};

#endif  //_PIZZA_H
