//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PizzaType.h
//  @ Date : 11.06.2024
//  @ Author : 
//
//


#if !defined(_PIZZATYPE_H)
#define _PIZZATYPE_H

#include <string>
#include <iostream>
#include <map>

enum PizzaType {
	Amerykanska,
	Rzymska
};

#endif  //_PIZZATYPE_H
