//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rzymska.h
//  @ Date : 11.06.2024
//  @ Author :
//
//


#if !defined(_RZYMSKA_H)
#define _RZYMSKA_H

#include <string>
#include <iostream>
#include <map>
#include "Pizza.h"

class Rzymska : public Pizza {
public:
	Rzymska():Pizza(Rzymska) {}
	~Rzymska();
	virtual Pizza* clone()const{
	return new Rzymska;}
	void printPizza();
};

#endif  //_RZYMSKA_H
