//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Rzymska.cpp
//  @ Date : 11.06.2024
//  @ Author :
//
//


#include <string>
#include <iostream>
#include <map>
#include "Rzymska.h"
#include "Pizza.h"

Rzymska::Rzymska() {

}

Rzymska::~Rzymska() {

}

Pizza Rzymska::clone() {

}

void Rzymska::printPizza() {
    cout<<"Rzymska\n";
}

