//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Audiobook.h
//  @ Date : 19.03.2024
//  @ Author :
//
//


#if !defined(_AUDIOBOOK_H)
#define _AUDIOBOOK_H

#include <iostream>
using namespace std;

class Audiobook {
public:
    Audiobook();
	void attach();
	void Odtworz();
};

#endif  //_AUDIOBOOK_H
