//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Audiobook.cpp
//  @ Date : 19.03.2024
//  @ Author :
//
//


#include <iostream>
using namespace std;
#include "Audiobook.h"

 Audiobook::Audiobook() {

}

void Audiobook::attach() {

}

void Audiobook::Odtworz() {
    cout<<"Odtworz";

}

