//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Kursy.h
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#if !defined(_KURSY_H)
#define _KURSY_H

#include <iostream>
#include <string>
 using namespace std;

class Kursy {
public:
	string name;
	int topic;
};

#endif  //_KURSY_H
