//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Lektor.h
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#if !defined(_LEKTOR_H)
#define _LEKTOR_H

#include <iostream>
using namespace std;

class Lektor {
public:
	string name;
	void Czytaj();
};

#endif  //_LEKTOR_H
