//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Lektor.cpp
//  @ Date : 19.03.2024
//  @ Author : 
//
//


#include <iostream>
using namespace std;
#include "Lektor.h"

void Lektor::Czytaj() {
    cout<<"Czytaj";

}

