//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.h
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#if !defined(_STUDENT_H)
#define _STUDENT_H

#include <iostream>
#include <string>
 using namespace std;

class Student {
public:
	string name;
	void attach();
};

#endif  //_STUDENT_H
