//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Student.cpp
//  @ Date : 22.03.2024
//  @ Author : 
//
//


#include <iostream>
#include <string>
 using namespace std;
#include "Student.h"

void Student::attach() {

}

