//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SYSTEM.cpp
//  @ Date : 09.04.2024
//  @ Author : 
//
//


#include <iostream>
#include <string>
using namespace std;
#include "SYSTEM.h"

void SYSTEM::Uwierzyt() {

}

void SYSTEM::Zaloguj() {

}

void SYSTEM::Dodaj() {

}

