//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SYSTEM.h
//  @ Date : 09.04.2024
//  @ Author :
//
//


#if !defined(_SYSTEM_H)
#define _SYSTEM_H

#include <iostream>
#include <string>
#include <vector>
#include "USER.h"

using namespace std;


class SYSTEM {
public:
	void Uwierzyt();
	void Zaloguj();
	void Dodaj();
private:
	vector<USER*> tab;
};

#endif  //_SYSTEM_H
