//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : USER.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//


#include <iostream>
#include <string>
using namespace std;

#include "USER.h"

void USER::rejestruj() {
    cout<<"Podaj login: "<<endl;
    cin>>login;
    cout<<"Podaj haslo: "<<endl;
    cin>>password;




}

bool USER::loguj() {
    string tempLogin, tempPassword;
    cout << "Podaj login: " << endl;
    cin >> tempLogin;
    cout << "Podaj haslo: " << endl;
    cin >> tempPassword;

    if (tempLogin == login && tempPassword == password) {
        cout << "Zalogowano!" << endl;
        return true;
    } else {
        cout << "Nieprawid³owy login lub has³o!" << endl;
        return false;
    }
}



void USER::wyloguj() {
    cout << "Wylogowano!" << endl;

}

