//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : USER.h
//  @ Date : 09.04.2024
//  @ Author :
//
//


#if !defined(_USER_H)
#define _USER_H

#include <iostream>
#include <string>
using namespace std;


class USER {
public:
	void rejestruj();
	bool loguj();
	void wyloguj();

	string getLogin() const { return login; }
    string getPassword() const { return password; }
private:
	string login;
	string password;

};

#endif  //_USER_H
