//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : USER.cpp
//  @ Date : 09.04.2024
//  @ Author :
//
//


#include <iostream>
#include <string>
using namespace std;

#include "USER.h"

void USER::rejestruj() {
    cout<<"Podaj login: "<<endl;
    cin>>login;
    cout<<"Podaj haslo: "<<endl;
    cin>>password;




}

void USER::loguj() {
    cout<<"Podaj login: "<<endl;
    cout<<"Podaj haslo: "<<endl;

}

void USER::wyloguj() {


}

