//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Person.h
//  @ Date : 09.04.2024
//  @ Author : 
//
//


#if !defined(_PERSON_H)
#define _PERSON_H


class Person {
};

#endif  //_PERSON_H
