//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : studenci.h
//  @ Date : 09.04.2024
//  @ Author : 
//
//


#if !defined(_STUDENCI_H)
#define _STUDENCI_H

#include "Person.h"

class studenci : public Person {
};

#endif  //_STUDENCI_H
