//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Uczelnia.h
//  @ Date : 09.04.2024
//  @ Author : 
//
//


#if !defined(_UCZELNIA_H)
#define _UCZELNIA_H


class Uczelnia {
};

#endif  //_UCZELNIA_H
